version: '3.7'

services:

  china_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test_db
    ports:
      - "3308:3306"
    volumes:
      - C:\Users\sadi\GitHub\docker_database\china_data